pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Intialize') {
            steps {
                sh '''
                echo "PATH = ${PATH}"
                echo "M2_HOME = ${M2_HOME}"
                '''        
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Deploy-To-Tomcat'){
            steps{
                sh 'whoami'
                sh 'cp target/*.war /opt/tomcat/webapps/'
            }
        }
    }
}
