pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Intialize') {
            steps {
                sh '''
                echo "PATH = ${PATH}"
                echo "M2_HOME = ${M2_HOME}"
                '''        
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('DAST') {
            steps {
                
                sh '''
                
                x=`docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://\$(ip -f inet -o addr show docker0 | awk '{print \$4}'| cut -d '/' -f 1):8080/WebApp/ -l Medium`
                if echo "$x" | grep "High";then echo "failed";fi || true 
                
                '''
            }
        }
    }
}
